"""Generated SheetsFinance catalog dataclasses.

DO NOT EDIT MANUALLY.
Generated by scripts/generate_sf_catalog.py
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List


@dataclass
class MetricDef:
    name: str
    aliases: List[str] = field(default_factory=list)
    description: str = ''
    deprecated: bool = False


@dataclass
class CategoryDef:
    function: str
    display_name: str
    type_values: List[str] = field(default_factory=list)
    metrics: List[MetricDef] = field(default_factory=list)
    year_syntax: str = ''
    options: List[str] = field(default_factory=list)
    example: str = ''
    notes: str = ''


@dataclass
class FunctionDef:
    signature: str
    metrics: List[MetricDef] = field(default_factory=list)
    example: str = ''
    options: List[str] = field(default_factory=list)
    notes: str = ''
    periods: List[str] = field(default_factory=list)
    types: List[str] = field(default_factory=list)


__all__ = ['MetricDef', 'CategoryDef', 'FunctionDef']
