"""Generated SheetsFinance catalog facade.

DO NOT EDIT MANUALLY.
Generated by scripts/generate_sf_catalog.py
"""

from __future__ import annotations

from typing import Dict

try:
    from .sf_catalog_categories import SF_CATEGORIES
    from .sf_catalog_functions import OTHER_FUNCTIONS
    from .sf_catalog_types import CategoryDef, FunctionDef, MetricDef
except ImportError:
    from sf_catalog_categories import SF_CATEGORIES
    from sf_catalog_functions import OTHER_FUNCTIONS
    from sf_catalog_types import CategoryDef, FunctionDef, MetricDef

COMMON_OPTIONS: Dict[str, str] = {'NH': 'No header rows', 'NLI': 'No line item labels', '-': 'Reverse chronological ordering', 'calYear': 'Calendar years instead of fiscal', 'pad': 'Pad missing periods with empty columns'}


__all__ = [
    'MetricDef',
    'CategoryDef',
    'FunctionDef',
    'SF_CATEGORIES',
    'OTHER_FUNCTIONS',
    'COMMON_OPTIONS',
]
